version: '3'

networks:
  uptime-link:
    driver: bridge

services:

  nginx:
    image: nginx:1.23.3-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - uptime-link
    links:
      - uptime
    volumes:
      - /bwg-uptime/config-files/cert/default.conf:/etc/nginx/conf.d/default.conf
      - /bwg-uptime/config-files/cert/4bee-decrypted.key:/etc/nginx/cert/uptime-cert-decrypted.key
      - /bwg-uptime/config-files/cert/4bee-cert.crt:/etc/nginx/cert/uptime-cert.crt

  uptime:
    image: guisousa/uptime:3.4
    container_name: uptime
    ports:
      - "3001"
    networks:
      - uptime-link
    volumes:
      - /bwg-uptime/volume:/app/data
